<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <section class="py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="row gx-4 gx-lg-5 align-items-center">
                <?php $html = "";
                error_reporting(0);
                $html .= '<div class="col-md-6"> <img class="card-img-top setimg" src="//covers.openlibrary.org/b/olid/' . $img . '.jpg" alt="Card image"></div>
    <div class="col-md-6">

        <h1 class="display-5 fw-bolder">' . $data['title'] . '</h1>
        <div class="fs-5 mb-5">


        </div>
        <p class="lead ">' . $data['authors'][0]['name'] . '</p>
        <p class="lead ">' . $data['publishers'][0] . '</p>
        <div class="d-flex">';
        if (!empty($gid)) {
        $html .= '<a class="btn btn-success" href="https://www.google.co.in/books/edition/_/'.$gid.'?hl=en">Open From Google</a>
        </div>
    </div>';
        }
                ?>
                <?php echo $html; ?>
            </div>
        </div>
    </section>
</body>

</html>